---
version: '3'

services:

  #
  # entry point to "public" services or APIs
  #

  gateway:
    build:
      context: sidecar
    volumes:
      - "./envoy.yaml:/etc/envoy.yaml"
    networks:
      - envoymesh
    ports:
      - "8000:9080"  # gateway
      - "8001:9090"  # envoy admin


  #
  # base services ~ not exposed via front envoy, but via sidecar proxy
  # i.e. these services are consumed by the application services
  #

  redis_sc:
    build:
      context: sidecar
    volumes:
      - "./redis/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - redis_sc
    links:
      - redis
    ports:
      - "8010:9080"  # service
      - "8011:9090"  # envoy admin

  redis:
    build:
      context: redis
    volumes:
      - "redis_data:/data"
    networks:
      envoymesh:
        aliases:
          - redis
    ports:
      - "8012:6379"  # service
    env_file:
      - "./.env"

  postgres_sc:
    build:
      context: sidecar
    volumes:
      - "./postgres/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - postgres_sc
    links:
      - postgres
    ports:
      - "8020:9080"  # service
      - "8021:9090"  # envoy admin

  postgres:
    build:
      context: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    networks:
      envoymesh:
        aliases:
          - postgres
    ports:
      - "8022:5432"  # service
    env_file:
      - "./.env"

  rabbitmq_sc:
    build:
      context: sidecar
    volumes:
      - "./rabbitmq/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - rabbitmq_sc
    links:
      - rabbitmq
    ports:
      - "8030:9080"  # service
      - "8031:9090"  # envoy admin

  rabbitmq:
    build:
      context: rabbitmq
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      envoymesh:
        aliases:
          - rabbitmq
    ports:
      - "8032:5672"   # service  4369 5671 5672 25672
      - "8033:15671"  # rabbimq admin    15671 15672
    env_file:
      - "./.env"


  #
  # example services
  #

  # HTTP service (backed by httpbin)

  http_service_sc:
    build:
      context: sidecar
    volumes:
      - "./http_service/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - http_service_sc
    links:
      - http_service
    ports:
      - "8010:9080"  # service
      - "8011:9090"  # envoy admin

  http_service:
    build:
      context: http_service
    networks:
      envoymesh:
        aliases:
          - http_service
    ports:
      - "8050:8080"  # direct connection for debugging
    env_file:
      - "./.env"

  # TODO



networks:
  envoymesh: {}

volumes:
  redis_data: {}
  postgres_data: {}
  rabbitmq_data: {}
