---
version: '2'

networks:
  envoymesh: {}

services:

  front-envoy:
    build:
      context: .
    volumes:
      - "./envoy.json:/etc/envoy.json"
    networks:
      - envoymesh
    ports:
      - "8000:8000"  # api
      - "8001:8001"  # admin

  service1:
    build:
      context: httpbin
    command: gunicorn -b 0.0.0.0:8080 httpbin:app --log-level DEBUG
    volumes:
      - "./httpbin:/httpbin"
      - "./httpbin/httpbin:/usr/local/lib/python3.6/site-packages/httpbin"
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - 8080
    ports:
      - "9090:8080"

  service2:
    build:
      context: httpbin
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - 8080

  service3:
    build:
      context: httpbin
    networks:
      envoymesh:
        aliases:
          - service3
    environment:
      - SERVICE_NAME=3
    expose:
      - 8080

  service4:
    build:
      context: httpbin
    networks:
      envoymesh:
        aliases:
          - service4
    environment:
      - SERVICE_NAME=4
    expose:
      - 8080
