---
version: '3'

services:

  #
  # entry point to "public" services or APIs
  #

  gateway:
    build:
      context: sidecar
    volumes:
      - "./envoy.yaml:/etc/envoy.yaml"
    networks:
      - envoymesh
    ports:
      - "8000:9080"  # gateway
      - "8001:9090"  # envoy admin
    links:
      - http_service_sc
      - redis_service_sc
      - postgres_service_sc
      - rabbitmq_service_sc

  #
  # base services ~ not exposed via front envoy, but via sidecar proxy
  # i.e. these services are consumed by the application services
  #

  redis_sc:
    build:
      context: sidecar
    volumes:
      - "./redis/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - redis_sc
    links:
      - redis
    ports:
      - "8010:9080"  # service
      - "8011:9090"  # envoy admin

  redis:
    build:
      context: redis
    volumes:
      - "redis_data:/data"
    networks:
      - envoymesh
    ports:
      - "8012:6379"  # service
    env_file:
      - "./.env"

  postgres_sc:
    build:
      context: sidecar
    volumes:
      - "./postgres/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - postgres_sc
    links:
      - postgres
    ports:
      - "8020:9080"  # service
      - "8021:9090"  # envoy admin

  postgres:
    build:
      context: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    networks:
      - envoymesh
    ports:
      - "8022:5432"  # service
    env_file:
      - "./.env"

  rabbitmq_sc:
    build:
      context: sidecar
    volumes:
      - "./rabbitmq/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - rabbitmq_sc
    links:
      - rabbitmq
    ports:
      - "8030:9080"  # service
      - "8031:9090"  # envoy admin

  rabbitmq:
    build:
      context: rabbitmq
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - envoymesh
    ports:
      - "8032:5672"   # service
      - "8033:15672"  # rabbimq admin
    env_file:
      - "./.env"



  #
  # example services
  #

  # HTTP service (backed by httpbin)

  http_service_sc:
    build:
      context: sidecar
    volumes:
      - "./http_service/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - http_service_sc
    links:
      - http_service
    ports:
      - "8050:9080"  # service
      - "8051:9090"  # envoy admin

  http_service:
    build:
      context: http_service
    networks:
      - envoymesh
    ports:
      - "8052:8080"  # direct connection for debugging
    env_file:
      - "./.env"

  # Service using redis

  redis_service_sc:
    build:
      context: sidecar
    volumes:
      - "./redis_service/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - redis_service_sc
    links:
      - redis_service
    ports:
      - "8060:9080"  # service
      - "8061:9090"  # envoy admin

  redis_service:
    build:
      context: redis_service
    networks:
      - envoymesh
    links:
      - redis_sc
    ports:
      - "8062:8080"  # direct connection for debugging
    env_file:
      - "./.env"

  # Service using Postgres

  postgres_service_sc:
    build:
      context: sidecar
    volumes:
      - "./postgres_service/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - postgres_service_sc
    links:
      - postgres_service
    ports:
      - "8070:9080"  # service
      - "8071:9090"  # envoy admin

  postgres_service:
    build:
      context: postgres_service
    networks:
      - envoymesh
    links:
      - postgres_sc
    ports:
      - "8072:8080"  # direct connection for debugging
    env_file:
      - "./.env"

  # Service using rabbitmq

  rabbitmq_service_sc:
    build:
      context: sidecar
    volumes:
      - "./rabbitmq_service/envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
        aliases:
          - rabbitmq_service_sc
    links:
      - rabbitmq_service
    ports:
      - "8080:9080"  # service
      - "8081:9090"  # envoy admin

  rabbitmq_service:
    build:
      context: rabbitmq_service
    networks:
      - envoymesh
    links:
      - rabbitmq_sc
    ports:
      - "8082:8080"  # direct connection for debugging
    env_file:
      - "./.env"

networks:
  envoymesh: {}

volumes:
  redis_data: {}
  postgres_data: {}
  rabbitmq_data: {}
